from manim import *

# Styling configs
BACKGROUND = '#141B2D'
HIGHLIGHT_COLOR = '#FACAFD'
HIGHLIGHT_TEXT = BACKGROUND
DELETE_COLOR = '#FF5454'
WIDTH = 5
FONT_SIZE = 0.6
VALUE_SIZE = 25
TITLE_SIZE = 70
TITLE_POSITION = UP*2.5+LEFT*4
RADIUS = 0.35
TABLE_SIDE_LENGTH = 0.7
SM_STROKE_WIDTH = 3     # For surrounding table
FONT = "Karla"

# Code block
SHIFT_RIGHT_UNIT = 3
SHIFT_LEFT_UNIT = 3
CODE_BLOCK_WIDTH_PADDING = 0.4
CODE_BLOCK_HEIGHT_PADDING  = 0
CODE_LINE_SPACING = 1
CODE_FONT = "Source Code Pro"

# Legend
LEGEND_SIZE = 16
SM_RADIUS = 0.1
LEGEND_BUFF = 0.1
LEGEND_STROKE_WIDTH = 1.5
PINK3 = '#F4E1F5'
PINK2 = '#FACAFD'
PINK1 = '#E79BEC'
BLUE1 = '#6BE0EC'
GRAY = '#F3F4F5'
GRAY_OUT = '#878EA0'
GREEN = '#09D542'
RED = '#FF5454'

# Graph
WIDTH_TOPOLOGICAL_GRAPH = 6
EDGE_COLOR = PINK3
EDGE_STROKE_COLOR = BACKGROUND
EDGE_STROKE_WIDTH = 0
LINE_COLOR = GRAY
WEIGHT_SIZE = 20
WEIGHT_CIRCLE_RADIUS = 0.15
WEIGHT_WEIGHT = BOLD

# Demo
EXAMPLE_SIZE = 27
TITLE_SIZE_FOR_DEMO = 18


# animate_graph.py -> range
FINAL_WIDTH = 6
FINAL_HEIGHT = 5

