from manim import *

# Styling configs
LINE_COLOR = '#F3F4F5'
BACKGROUND = '#141B2D'
HIGHLIGHT_COLOR = '#FACAFD'
HIGHLIGHT_TEXT = BACKGROUND
DELETE_COLOR = '#FF5454'
WIDTH = 5
FONT_SIZE = 0.6
VALUE_SIZE = 25
TITLE_SIZE = 0.8
TITLE_POSITION = UP*2.5+LEFT*4
RADIUS = 0.35
TABLE_SIDE_LENGTH = 0.7
SHIFT_RIGHT_UNIT = 3
SHIFT_LEFT_UNIT = 3.5
CODE_BLOCK_WIDTH_PADDING = 0.4
CODE_BLOCK_HEIGHT_PADDING  = 0.2

PINK3 = '#F4E1F5'
PINK1 = '#E79BEC'
BLUE1 = '#6BE0EC'

FONT = "Karla"