from manim import *

# Styling configs
WATERMARK_OPACITY = 0.02
BACKGROUND = '#141B2D'
HIGHLIGHT_COLOR = '#FACAFD'
HIGHLIGHT_TEXT = BACKGROUND
DELETE_COLOR = '#FF5454'
WIDTH = 5   # Stroke width of nodes
FONT_SIZE = 0.6
SMALL_FONT_SIZE = 20
VALUE_SIZE = 25 # For node value
KEY_SIZE = VALUE_SIZE * 0.9
M_VALUE_SIZE = VALUE_SIZE * 2    # For iterator
TINY_VALUE_SIZE = VALUE_SIZE - 8 # For music note
TITLE_SIZE = 72
TITLE_POSITION = UP*2.5+LEFT*4
SMALL_RADIUS = 0.31   # For no code version
RADIUS = 0.35   # For code version
TABLE_SIDE_LENGTH = 0.7
SM_STROKE_WIDTH = 3     # For surrounding table
FONT = "Karla"
FONT_NOTE = 'Georgia'

# Code block
# SHIFT_RIGHT_UNIT = 3
# SHIFT_LEFT_UNIT = -3
# SHIFT_UP_UNIT = -0.1
SHIFT_RIGHT_UNIT = 0
SHIFT_LEFT_UNIT = 0
SHIFT_UP_UNIT = 0
CODE_BLOCK_WIDTH_PADDING = 0.4
CODE_BLOCK_HEIGHT_PADDING  = 0
CODE_LINE_SPACING = 1
CODE_FONT = "Source Code Pro"
BOX_STROKE_WIDTH = 2

# Legend
LEGEND_SIZE = 16
SM_RADIUS = 0.1
LEGEND_BUFF_MICRO = 0.2
LEGEND_BUFF_MACRO = 0.2
LEGEND_BUFF_MACRO_HORIZONTAL = 0.4
LEGEND_STROKE_WIDTH = 1.5
LEGEND_GRAPH_BUFF = 0.3
PINK3 = '#F4E1F5'
PINK2 = '#FACAFD'
PINK1 = '#E79BEC'
BLUE1 = '#72DDF7'
# BLUE1 = '#6BE0EC'
GRAY = '#F3F4F5'
GRAY_OUT = '#878EA0'
GREEN = '#07AB35'
PURPLE = '#8A3AFF'
# RED = '#E60966'
RED = '#CC085A'
PURPLE = '#BA4CE2'
PINK4 = '#EDC0E8'   # exclusively reserved for the fill_color of a highlighted node
PINK5 = '#D163CD'   # exclusively reserved for the stroke_color of a highlighted node

# Graph
WIDTH_TOPOLOGICAL_GRAPH = 6
EDGE_COLOR = PINK3
EDGE_STROKE_COLOR = BACKGROUND
EDGE_STROKE_WIDTH = 0
EDGE_HIGHLIGHT_STROKE_WIDTH = WIDTH + 12
EDGE_HIGHLIGHT_STROKE_WIDTH_FOR_DIGRAPH = EDGE_HIGHLIGHT_STROKE_WIDTH
EDGE_HIGHLIGHT_STROKE_WIDTH_FOR_DIGRAPH_CURVY = WIDTH + 5
LINE_COLOR = GRAY
WEIGHT_SIZE = 20
WEIGHT_CIRCLE_RADIUS = 0.2
WEIGHT_WEIGHT = BOLD
# TIP_LENGTH_FOR_CURVED_LINE = 0.3 # for normal graph
TIP_LENGTH_FOR_CURVED_LINE = 0.2 # for music graph
TIP_LENGTH_FOR_STRAIGHT_LINE = TIP_LENGTH_FOR_CURVED_LINE / 2
EDGE_RADIUS = 2.8 # for directed graph, the larger the straighter

# Music graph
NODE_BUFF = 1.5

# Node
NODE_NAME_BACKGROUND_SIZE = 45
NODE_NAME_BACKGROUND_OPACITY = 0.3
NODE_NAME_BACKGROUND_COLOR = PINK1
NODE_NAME_BACKGROUND_WEIGHT = NORMAL
HIGHLIGHT_STROKE = '#FDDDFF'
HIGHLIGHT_RECTANGLE_WIDTH = 1.9*RADIUS
NODE_HIGHLIGHT_STROKE_WIDTH = WIDTH + 2
LABEL_SQUARE_SIZE = 0.25

# Demo
EXAMPLE_SIZE = 27
TITLE_SIZE_FOR_DEMO = 18

# animate_graph.py -> to scale the position to fit
FINAL_LENGTH = 3.5

# Utils
LIGHT_COLORS = [PINK2, '#b1c7fd', '#ddfdb1', '#fdb1f3', '#b1fdf0', '#fddab1', '#c4b1fd', '#fdb1ca', '#b1e1fd', '#fdc1b1', '#edb1fd', '#E5E5E5']
MULTI_COLORS = [PINK1, '#ECD59B', '#9BA3EC']
# MULTI_COLORS = [PINK1, '#9CEBED', '#9BA3EC']
SURROUNDING_BOX_WIDTH = LEGEND_STROKE_WIDTH

# Fairytale
COMPANY_CHARACTER_BUFF = 0.15
LEGEND_CHARACTER_BUFF = 0.6
CHARACTER_EDGE_BUFFER = 0.6
CHARACTER_TO_EDGE_SCALE = 0.6
WAIT_TIME_AFTER = 1
MST_COMPANY = (PINK1, '#32264F')
SP_COMPANY = (BLUE1, '#1D2E41')
CHARACTER_CHARACTER_BUFF_VERTICAL = 0.2
CONDITION_MARK_SHIFT_RIGHT_UNIT = 0.57
COMPANY_FONT_SIZE_TOP_RIGHT = 20